### ISSUE TITLE
The demo does not work in mobile devices

### ISSUE THREAD

**Issue by aniirban101** [Avexis/fontalizer#1]
The demo that you had put in readme does not work in mobile/touch enabled devices. Also make sure the site is responsive.

**Comment by boyum** [comment]
As the `keydown` event doesn't really work with the virtual keyboard on touch devices, and the `change` event only fires once per change, this doesn't really work. Of course, someone could use a physical keyboard with these devices as well, but that's why we haven't made it very mobile-friendly.

If there's anything we have overlooked, we'll be happy to look into it - please chime in if you have any ideas!
